image:
  file: .gitpod.Dockerfile

tasks:
  - init: dotnet clean && dotnet build && dotnet test
    command: jq '.url = ${(echo gp url 3306)}' ./minify/dbConfig.json > temp.$$.json && mv tmp.$$.json ./minify/dbConfig.json

vscode:
  extensions:
    - muhammad-sammy.csharp@1.23.9:BMArOoGwWqKRrH6s4E2/AQ==