image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd minify && dotnet clean && dotnet build && dotnet test && cd ..
    command: jq '.ConnectionUrl = ${$(echo gp url 3306)}' ./minifyappsettings.json > temp.$$.json && mv tmp.$$.json ./minify/dbConfig.json

vscode:
  extensions:
    - muhammad-sammy.csharp@1.23.9:BMArOoGwWqKRrH6s4E2/AQ==